### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_INCLUDEDIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [shlomif/rinutils#5]
As per title: `librinutils.pc.in` has
```
prefix="@CMAKE_INSTALL_PREFIX@"
exec_prefix=${prefix}
libdir=${exec_prefix}/@RINUTILS_INSTALL_MYLIBDIR@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_INCLUDEDIR`. This leads to broken .pc files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by shlomif** [comment]
Thanks for the report! i'll try to investigate.

**Comment by shlomif** [comment]
@alexshpilkin : hi. Please check if it is fixed in the latest version.

**Comment by alexshpilkin** [comment]
@shlomif Thank you for the quick response! I can confirm that the value of `includedir` is now correct, but have to apologize for a misleading bug report: `libdir` is similarly affected. This should not really matter as it actually isn’t used for anything either (?..), but you might want to take care of it nevertheless.

(I’m looking at my own temporary fix and it *does* change `libdir` as well, but apparently my memory of doing that did not survive the couple of minutes that passed between writing it and filing the bug report here. :( )

**Comment by shlomif** [comment]
hi Alex,

On Fri, 27 May 2022 06:14:55 -0700
Alex Shpilkin ***@***.***> wrote:

> @shlomif Thank you for the quick response! I can confirm that the value of
> `includedir` is now correct, but have to apologize for a misleading bug
> report: `libdir` is similarly affected. This should not really matter as it
> actually isn’t used for anything either (?..), but you might want to take
> care of it nevertheless.
> 
> (I’m looking at my own temporary fix and it *does* change `libdir` as well,
> but apparently my memory of doing that did not survive the couple of minutes
> that passed between writing it and filing the bug report here. :( )
> 

thanks! i may get to that,

-- 

Shlomi Fish       https://www.shlomifish.org/
https://github.com/shlomif/what-you-should-know-about-automated-testing

"Consistency requires you to be as ignorant today as you were a year ago."
    — Bernard Berenson, https://en.wikiquote.org/wiki/Consistency

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@alexshpilkin : hi! Please check 0.10.3

**Comment by alexshpilkin** [comment]
@shlomif Brilliant, thank you!
